# Generated by Django 3.0 on 2019-12-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcode',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='验证码时间'),
        ),
    ]
