# Generated by Django 3.0 on 2019-12-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191206_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodimage',
            name='filename',
        ),
        migrations.AddField(
            model_name='good',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='商品说明'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='is_edit',
            field=models.BooleanField(default=True, verbose_name='草稿'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_sell',
            field=models.BooleanField(default=False, verbose_name='在售'),
        ),
    ]
