# Generated by Django 3.0 on 2019-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191206_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsize',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='序号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='label',
            field=models.CharField(max_length=30, unique=True, verbose_name='英文标签'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='描述'),
        ),
    ]
