# Generated by Django 3.0 on 2019-12-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_collection_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Good', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览足迹',
            },
        ),
    ]
