# Generated by Django 3.0 on 2019-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20191214_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='express_cmp',
            field=models.CharField(default='暂无', max_length=32, verbose_name='快递公司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_number',
            field=models.CharField(default='暂无', max_length=32, verbose_name='快递单号'),
        ),
    ]
