# Generated by Django 3.0 on 2019-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_collection_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, verbose_name='文件名路径')),
                ('count', models.PositiveIntegerField(verbose_name='订单条数')),
                ('is_finish', models.BooleanField(default=False, verbose_name='是否生成')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '订单报表',
            },
        ),
        migrations.AlterField(
            model_name='good',
            name='content',
            field=models.CharField(default='<ul><li>未定义内容</li></ul>', max_length=200, verbose_name='商品说明'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='good',
            name='title',
            field=models.CharField(default='未定义标题', max_length=100, verbose_name='标题'),
        ),
    ]
