# Generated by Django 3.0 on 2019-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20191215_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='path',
        ),
        migrations.AddField(
            model_name='report',
            name='filename',
            field=models.CharField(default=1, max_length=128, unique=True, verbose_name='文件名路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='订单条数'),
        ),
    ]
