# Generated by Django 3.0 on 2019-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20191215_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.CharField(max_length=128, verbose_name='文件名路径'),
        ),
    ]
