# Generated by Django 3.0 on 2019-12-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20191215_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filename',
        ),
    ]
