# Generated by Django 3.0 on 2019-12-15 18:36

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_report_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filename',
            field=models.CharField(default=builtins.id, max_length=128, verbose_name='文件名路径'),
            preserve_default=False,
        ),
    ]
