# Generated by Django 3.0 on 2019-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_report_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.CharField(max_length=128, unique=True, verbose_name='文件名路径'),
        ),
    ]
